# Site settings
# Change these to your info

url: "https://liuike.github.io"   # no trailing slash
baseurl: ""                       # empty for user sites (username.github.io repos)
title: "Liuike"
description: "Developer • Designer • Tinkerer"

# Build settings (safe GitHub Pages defaults)
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Collections (optional)
# collections:
#   projects:
#     output: true

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Excludes from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/

# Author/profile (used in templates)
author:
  name: "Liuike"
  email: "you@example.com"
  github: "Liuike"
  twitter: "your_handle"

# Navbar links for convenience
nav:
  - name: Home
    url: /
  - name: About
    url: /pages/about/
  - name: Projects
    url: /pages/projects/
  - name: Blog
    url: /

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
