source 'https://rubygems.org'

# Lock to the version GitHub Pages uses in production
# This brings in jekyll, kramdown, and the supported plugins

gem 'github-pages', group: :jekyll_plugins

group :development do
  gem 'webrick'    # needed for local `bundle exec jekyll serve`
end
